[package]
name = "simple"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
ssg = { path = "../.." }
tokio = { version = "1.24.1", features = ["macros", "rt-multi-thread"] }
