name: Flake checker CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: Nix and Rust checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check flake.lock
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          fail-mode: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Check Nix formatting
        run: nix develop --command check-nixpkgs-fmt
      - name: Check Rust formatting
        run: nix develop --command cargo fmt --check
      - name: Clippy
        run: nix develop --ccommand cargo clippy
      - name: Flake check
        run: nix flake check

  rust-build-test:
    name: Build and test Rust
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: cargo build
        run: nix develop --command cargo build --release
      - name: cargo test
        run: nix develop -c cargo test
